/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import BD.ConnectionBD;
import Clases.Board;
import Clases.SoldNumbers;
import Clases.Ticket;
import Clases.TicketTime;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Joha
 */
public class ticketCodScanDelete extends javax.swing.JFrame {

    /**
     * Creates new form ticketCodScanDelete
     */
    private DefaultListModel numbersList = new DefaultListModel();
    private DefaultListModel moneyList = new DefaultListModel();
    private int idToFindTicket;
    
    public ticketCodScanDelete() {
        initComponents();
        visibleFalseComponents(false);        
    }

    public void setAll(){
        mensaje.setForeground(Color.red);
        barCodeTxt.setText("");
        dateTxt.setText("");                
        ticketIdTxt.setText("");
        timeTxt.setText("");
        totalTxt.setText("");        
        mensaje.setText("");
        numbersList= new DefaultListModel();
        moneyList= new DefaultListModel();
        numbersListTxt.setModel(numbersList);
        moneyListTxt.setModel(moneyList);        
    }
    
    
    public void visibleFalseComponents(boolean bool){
        labelBarCode.setVisible(bool);
        barCodeTxt.setVisible(bool);
        
        labelDate.setVisible(bool);
        dateTxt.setVisible(bool);                
        
        labelIdTicket.setVisible(bool);
        ticketIdTxt.setVisible(bool);
        
        labelTime.setVisible(bool);
        timeTxt.setVisible(bool);
        
        labelTotal.setVisible(bool);
        totalTxt.setVisible(bool);        
        
        deleteButton.setVisible(bool);
        printButton.setVisible(bool);             
        panel.setVisible(bool);
    }
    
    public void findIdTicket(){
        String idTicket= idFindTxt.getText();
        if(idTicket.equals("")){
            //JOptionPane.showMessageDialog(null,"Se debe de ingresar un dato","Error",JOptionPane.INFORMATION_MESSAGE);
            mensaje.setText("Se debe de ingresar un dato");
            return;            
        }
        
        idToFindTicket= Integer.parseInt(idTicket);                       
        ConnectionBD con= new ConnectionBD();                                
        Ticket ticket= con.getTicketInformationFind(idToFindTicket);        
        if(ticket== null){            
            //JOptionPane.showMessageDialog(null,"El tiquete no es válido","Error",JOptionPane.INFORMATION_MESSAGE);
            mensaje.setText("El tiquete no es válido");
            return;
        }                
        List<SoldNumbers>lista=con.GetNumberSoldFromTiicket(idTicket);                
        for (int i = 0; i < lista.size(); i++) {
            numbersList.addElement(lista.get(i).getNumber());
            moneyList.addElement(lista.get(i).getMoneySold());                        
        }
        if(lista.size()>0){
            int idBoard= lista.get(0).getBoard();
            Board board= con.getBoardInformationFind(idBoard);
            barCodeTxt.setText(String.valueOf(board.getBarCode()));
        }
        numbersListTxt.setModel(numbersList);
        moneyListTxt.setModel(moneyList);
        totalTxt.setText(String.valueOf(ticket.getTicketTotalAmount()));        
        
        TicketTime tiempo= con.getTicketTime(idTicket);
        timeTxt.setText(tiempo.getTime());                        
        
        dateTxt.setText(ticket.getDate());                         
        ticketIdTxt.setText(idTicket);        
        
        visibleFalseComponents(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idFindTxt = new javax.swing.JTextField();
        labelTicket = new javax.swing.JLabel();
        findTicketButton = new javax.swing.JButton();
        labelTime = new javax.swing.JLabel();
        labelIdTicket = new javax.swing.JLabel();
        labelBarCode = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        ticketIdTxt = new javax.swing.JTextField();
        barCodeTxt = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        timeTxt = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        labelNumber = new javax.swing.JLabel();
        labelMoney = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moneyListTxt = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        numbersListTxt = new javax.swing.JList<>();
        deleteButton = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTicket.setText("Tiquete");

        findTicketButton.setText("Buscar");
        findTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTicketButtonActionPerformed(evt);
            }
        });

        labelTime.setText("Tiempo");

        labelIdTicket.setText("Tiquete");

        labelBarCode.setText("Código Barras");

        labelTotal.setText("Total");

        labelDate.setText("Fecha");

        dateTxt.setEditable(false);

        ticketIdTxt.setEditable(false);

        barCodeTxt.setEditable(false);

        totalTxt.setEditable(false);

        timeTxt.setEditable(false);

        printButton.setText("Imprimir");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        labelNumber.setText("Número");

        labelMoney.setText("Plata");

        moneyListTxt.setEnabled(false);
        jScrollPane2.setViewportView(moneyListTxt);

        numbersListTxt.setEnabled(false);
        jScrollPane1.setViewportView(numbersListTxt);

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(labelNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMoney)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(53, 53, 53))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelMoney))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNumber)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mensaje.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(labelTicket)
                        .addGap(18, 18, 18)
                        .addComponent(idFindTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findTicketButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(printButton)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDate)
                            .addComponent(labelTime)
                            .addComponent(labelTotal)
                            .addComponent(labelBarCode)
                            .addComponent(labelIdTicket))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(timeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barCodeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketIdTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(mensaje)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTicketButton)
                    .addComponent(idFindTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTicket))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mensaje)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ticketIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdTicket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBarCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTime))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDate))
                        .addGap(60, 60, 60)
                        .addComponent(printButton)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTicketButtonActionPerformed
        // TODO add your handling code here:
        setAll();
        findIdTicket();        
    }//GEN-LAST:event_findTicketButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:        
        ConnectionBD con= new ConnectionBD();                                
        con.deleteTicket(idToFindTicket);
        setAll();
        visibleFalseComponents(false);
        mensaje.setText("El tiquete ha sido eliminado");
        mensaje.setForeground(Color.green);
        
        /*Selling selling = new Selling();
        selling.setVisible(true);
        selling.setLocationRelativeTo(null);
        selling.setExtendedState(JFrame.MAXIMIZED_BOTH);
        selling.setCompanyName("Bran-Labs");
        dispose();*/
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:    
        TicketWindowPrint oClienteCrear = new TicketWindowPrint(idToFindTicket);
        oClienteCrear.setAlwaysOnTop(true);
        oClienteCrear.setVisible(true);
        oClienteCrear.setLocationRelativeTo(null);        
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketCodScanDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketCodScanDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketCodScanDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketCodScanDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketCodScanDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCodeTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton findTicketButton;
    private javax.swing.JTextField idFindTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBarCode;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelIdTicket;
    private javax.swing.JLabel labelMoney;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JLabel labelTicket;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel mensaje;
    private javax.swing.JList<String> moneyListTxt;
    private javax.swing.JList<String> numbersListTxt;
    private javax.swing.JPanel panel;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField ticketIdTxt;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables
}
