/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Clases.Tiquete;
import Clases.Conexion;
import Clases.NumerosVendidos;
import Clases.Tiempo;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Joha
 */
public class VentanaTiquete extends javax.swing.JFrame {
    
    /**
     * Creates new form VentanaTiquete
     */
    private DefaultListModel numeros = new DefaultListModel();
    private DefaultListModel plata = new DefaultListModel();
    private int sumaMontoTotal= 0;
    
    public VentanaTiquete(int accion) {
        initComponents();
        if(accion== 1){
            mostrarInformacionPagar();
        }                
        else{
            mostrarInformacionImpresionTotalUnico();
        }
    }
    
    public void mostrarInformacionImpresionTotalUnico(){
        Conexion con= new Conexion();
        Tiquete tiquete= con.obtenerInformacionTiquete();        
        tiqueteTxt.setText(String.valueOf(tiquete.getNumero()));
        fechaTxt.setText(tiquete.getFechaTiquete()); 
        codigoBarraTxt.setText(String.valueOf(tiquete.getCodigoBarra()));
        List<NumerosVendidos>lista=con.obtenerNumerosVendidosDeUnTiquete(String.valueOf(tiquete.getNumero()));                
        for (int i = 0; i < lista.size(); i++) {
            numeros.addElement(lista.get(i).getNumero());
            plata.addElement(lista.get(i).getPlataVendido());            
            sumaMontoTotal= lista.get(i).getNumero()+sumaMontoTotal;
        }
        listaNumeros.setModel(numeros);
        listaPlata.setModel(plata);
        plataTotalTxt.setText(String.valueOf(sumaMontoTotal));
        Tiempo tiempo= con.obtenerTiempoTiquete(String.valueOf(tiquete.getNumero()));
        tiempoTxt.setText(tiempo.getTiempo());
    }
    
    public void mostrarInformacionPagar(){
        Conexion con= new Conexion();
        Tiquete tiquete= con.obtenerInformacionTiquete();        
        
        tiqueteTxt.setText(String.valueOf(tiquete.getNumero()));
        fechaTxt.setText(tiquete.getFechaTiquete()); 
        codigoBarraTxt.setText(String.valueOf(tiquete.getCodigoBarra()));
        List<NumerosVendidos>lista=con.obtenerNumerosVendidosDeUnTiquete(String.valueOf(tiquete.getNumero()));                
        for (int i = 0; i < lista.size(); i++) {
            numeros.addElement(lista.get(i).getNumero());
            plata.addElement(lista.get(i).getPlataVendido());            
            sumaMontoTotal= lista.get(i).getPlataVendido()+sumaMontoTotal;
        }
        listaNumeros.setModel(numeros);
        listaPlata.setModel(plata);
        plataTotalTxt.setText(String.valueOf(sumaMontoTotal));
        Tiempo tiempo= con.obtenerTiempoTiquete(String.valueOf(tiquete.getNumero()));
        tiempoTxt.setText(tiempo.getTiempo());
        firmaLabelAbajo.setVisible(false);
        espacioFirma.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nombreComercioTxt = new javax.swing.JLabel();
        firmaTxt = new javax.swing.JLabel();
        tiqueteLaabel = new javax.swing.JLabel();
        tiempoLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        plataLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNumeros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPlata = new javax.swing.JList<>();
        totalLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        condicionesTxt = new javax.swing.JTextArea();
        firmaLabelAbajo = new javax.swing.JLabel();
        espacioFirma = new javax.swing.JSeparator();
        codigoBarraTxt = new javax.swing.JLabel();
        tiqueteTxt = new javax.swing.JLabel();
        tiempoTxt = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JLabel();
        plataTotalTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonImprimir.setText("Imprimir");
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreComercioTxt.setText("Nombre del comercio");

        firmaTxt.setText("Firma");

        tiqueteLaabel.setText("Tiquete");

        tiempoLabel.setText("Tiempo");

        fechaLabel.setText("Fecha");

        numeroLabel.setText("Número");

        plataLabel.setText("Plata");

        listaNumeros.setEnabled(false);
        listaNumeros.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listaNumeros);

        listaPlata.setEnabled(false);
        jScrollPane2.setViewportView(listaPlata);

        totalLabel.setText("Total");

        condicionesTxt.setEditable(false);
        condicionesTxt.setColumns(20);
        condicionesTxt.setRows(5);
        condicionesTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        condicionesTxt.setEnabled(false);
        jScrollPane3.setViewportView(condicionesTxt);

        firmaLabelAbajo.setText("Firma");

        codigoBarraTxt.setText("CódigoBarra");

        tiqueteTxt.setText("txtTiquete");

        tiempoTxt.setText("txtTiempo");

        fechaTxt.setText("txtFecha");

        plataTotalTxt.setText("montoTotal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(codigoBarraTxt)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGap(63, 63, 63))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(plataTotalTxt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firmaTxt)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(firmaLabelAbajo)
                        .addGap(18, 18, 18)
                        .addComponent(espacioFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(numeroLabel)
                        .addGap(79, 79, 79)
                        .addComponent(plataLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreComercioTxt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaLabel)
                                    .addComponent(tiempoLabel)
                                    .addComponent(tiqueteLaabel))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tiempoTxt)
                                    .addComponent(tiqueteTxt)
                                    .addComponent(fechaTxt))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(firmaTxt)
                .addGap(18, 18, 18)
                .addComponent(nombreComercioTxt)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tiqueteTxt)
                            .addComponent(tiqueteLaabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tiempoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaLabel)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroLabel)
                            .addComponent(plataLabel))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(plataTotalTxt))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(espacioFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(firmaLabelAbajo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45)
                .addComponent(codigoBarraTxt)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonImprimir)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTiquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonImprimir;
    private javax.swing.JLabel codigoBarraTxt;
    private javax.swing.JTextArea condicionesTxt;
    private javax.swing.JSeparator espacioFirma;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel fechaTxt;
    private javax.swing.JLabel firmaLabelAbajo;
    private javax.swing.JLabel firmaTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaNumeros;
    private javax.swing.JList<String> listaPlata;
    private javax.swing.JLabel nombreComercioTxt;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JLabel plataLabel;
    private javax.swing.JLabel plataTotalTxt;
    private javax.swing.JLabel tiempoLabel;
    private javax.swing.JLabel tiempoTxt;
    private javax.swing.JLabel tiqueteLaabel;
    private javax.swing.JLabel tiqueteTxt;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
